name: rincon_sabor_flutter
description: "Proyecto de App para el Restaurante Rincon del Sabor"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  accordion: ^2.6.0
  image_picker: ^1.1.2
  provider: ^6.1.5
  socket_io_client: ^3.1.2
  syncfusion_flutter_charts: ^29.2.11
  chart_sparkline: ^1.1.1
  month_picker_dialog: ^6.0.3
  flutter_launcher_icons: ^0.14.4
  ml_algo: ^16.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.26.2   # 👈 para asegurar compatibilidad con los tests

flutter:
  uses-material-design: true

  assets:
    - assets/env/
    - assets/
    - assets/image/
    - assets/data/historialpedidos.json
    - assets/cocina_es_android_v3_0_0.ppn
    - assets/porcupine_params_es.pv

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf

flutter_icons:
  android: true
  ios: false
  image_path: "assets/iconApp.png"
